alias proxy='export all_proxy=socks5://127.0.0.1:1086'
alias unproxy='unset all_proxy'
alias list-myshell='bash ~/Desktop/summary/my-shell/list-myshell.sh'
alias clone-project='bash ~/Desktop/summary/my-shell/clone-project.sh'
alias update-study='bash ~/Desktop/summary/my-shell/update-study.sh'
alias nacos-start='sh ~/Desktop/nacos/bin/startup.sh -m standalone'
alias nacos-stop='sh ~/Desktop/nacos/bin/shutdown.sh'
