apiVersion: v1
kind: ReplicaSet
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        resources:
          requests:
            cpu: 200m
            memory: 64M
          limits:
            cpu: 0.5
            memory: 256Mi