apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
      labels:
        app: app-demo
        tier: frontend
    spec:
      volumes:
        - name:  datavol
          hostPath:
            path: /mydata-data
      containers:
      - name: tomcat-demo
        image: tomcat
        volumeMounts:
          - name:  datavol
            mountPath:  /mydata-data
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      