apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  cassandra
  labels:
    name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cassandra
  template:
    metadata:
      labels:
        name: cassandra
    spec:
      containers:
      - command:
        - /run.bash
        resources:
          limits:
            cpu: 0.5
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: grc.io/google_containers/cassandra:v5
        name: cassandra
        ports:
        - containerPort: 9042
          name: cql
        - containerPort: 9160
          name: thrift
        volumeMounts:
          - name:  data
            mountPath:  /cassandra_data
      volumes:
        - name:  data
          emptyDir: {}