apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  initContainers:
  - name: install
    image: busybox
    command:
    - wget
    - "-O"
    - "/work-dir/index.html"
    - http://www.baidu.com
    volumeMounts:
      - name:  workdir
        mountPath:  "/work-dir"
  containers:
    - image:  nginx
      name:  nginx
      ports:
      - containerPort: 80
      volumeMounts:
      - name:  workdir
        mountPath:  "/usr/share/nginx/html"
  dnsPolicy: Default
  volumes:
    - name: workdir
      emptyDir: {}